### ISSUE TITLE
Final Project Tracking History

### ISSUE THREAD

**Issue by gmyshkin** [JKDX4567/SSW-345-Projects-MBG#1]
- [x] First Milestone
- [ ] Profile diagrams
- [x] Class diagrams
- [x] Use at least one Design Pattern.  Name it and explain it in the code and with class diagrams.
- [ ] Component diagrams
- [ ] Deployment diagrams
- [ ] Package diagrams
- [ ] Object diagrams
- [ ] Composite structure diagrams
- [x] Activity diagrams
- [x] Use case diagrams (also very important)
- [x] Sequence diagrams
- [ ] Interaction diagrams
- [ ] Communication 
- [ ] Timing diagrams
- [ ] State machine diagrams
Working On:
PowerPoint Presentation
Diagrams for the powerpoint

**Comment by gmyshkin** [comment]
Classes that are currently being worked on: 
Investment - create a class for 
BankInvestment
ProjectInvestment
Database
InvestmentManager
Comparator
ProjectComparator
BankInvestmentComparator

Create Kanban Board on Github to place this info into

**Comment by JKDX4567** [comment]
All classes have been completed
